FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# Bundle app source
COPY . .

# building your code for production
RUN npx yarn install --production
RUN npx prisma generate

EXPOSE 4444
CMD [ "node", "index.js" ]
